pipeline {
    agent none
    stages {
        stage('Build') { // Define the stage.
            agent {
                docker {
                    image 'python:2-alpine' // The Python container becomes the agent that Jenkins uses to run the Build stage of your Pipeline project.
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py' // Runs the Python command to compile your application.
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
